version: "3.8"
services:
  auth:
    build: ./microservices/auth
    ports: ["5001:5000"]
  product:
    build: ./microservices/product
    ports: ["5002:5000"]
  order:
    build: ./microservices/order
    ports: ["5003:5000"]
  nginx:
    image: nginx:latest
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [auth, product, order]
